# Generated by Django 4.0.4 on 2022-06-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
    ]
